
-define(CACHE_RAW_MESSAGE, 0).
-define(CACHE_BLOCK_MESSAGE, 1).
-define(CACHE_REFERENCE_MESSAGE, 2).
-define(CACHE_REFERENCE_OK_MESSAGE, 3).
-define(CACHE_MISSED_REFERENCE_MESSAGE, 4).
-define(CACHE_MISSED_REFERENCE_INFO_MESSAGE, 5).
